const products = [
  {
    id: 1,
    image: "product1.webp",
    subImage1: "product1f.webp",
    subImage2: "product1s.webp",
    subImage3: "product1t.webp",
    name: "product1",
    title: "Women Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 2,
    image: "product2.webp",
    subImage1: "product2f.webp",
    subImage2: "product2s.webp",
    subImage3: "product2t.webp",
    name: "product2",
    title: "Women Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 3,
    image: "product3.webp",
    subImage1: "product3f.webp",
    subImage2: "product3s.webp",
    subImage3: "product3t.webp",
    name: "product3",
    title: "Men Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 4,
    image: "product4.webp",
    subImage1: "product4f.webp",
    subImage2: "product4s.webp",
    subImage3: "product4t.webp",
    name: "product4",
    title: "Women Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 5,
    image: "product5.webp",
    subImage1: "product5f.webp",
    subImage2: "product5s.webp",
    subImage3: "product5t.webp",
    name: "product5",
    title: "Women Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 6,
    image: "product6.webp",
    subImage1: "product6f.webp",
    subImage2: "product6s.webp",
    subImage3: "product6t.webp",
    name: "product6",
    title: "Watches",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 7,
    image: "product7.webp",
    subImage1: "product7f.webp",
    subImage2: "product7s.webp",
    subImage3: "product7t.webp",
    name: "product7",
    title: "Women Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 8,
    image: "product8.webp",
    subImage1: "product8f.webp",
    subImage2: "product8s.webp",
    subImage3: "product8t.webp",
    name: "product8",
    title: "Women Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 9,
    image: "product9.webp",
    subImage1: "product9f.webp",
    subImage2: "product9s.webp",
    subImage3: "product9t.webp",
    name: "product9",
    title: "Shoes",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 10,
    image: "product10.webp",
    subImage1: "product10f.webp",
    subImage2: "product10s.webp",
    subImage3: "product10t.webp",
    name: "product10",
    title: "Women Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 11,
    image: "product11.webp",
    subImage1: "product11f.webp",
    subImage2: "product11s.webp",
    subImage3: "product11t.webp",
    name: "product11",
    title: "Men Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 12,
    image: "product12.webp",
    subImage1: "product12f.webp",
    subImage2: "product12s.webp",
    subImage3: "product12t.webp",
    name: "product12",
    title: "Men Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 13,
    image: "product13.webp",
    subImage1: "product13f.webp",
    subImage2: "product13s.webp",
    subImage3: "product13t.webp",
    name: "product13",
    title: "Women Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 14,
    image: "product14.webp",
    subImage1: "product14f.webp",
    subImage2: "product14s.webp",
    subImage3: "product14t.webp",
    name: "product14",
    title: "Women Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 15,
    image: "product15.webp",
    subImage1: "product15f.webp",
    subImage2: "product15s.webp",
    subImage3: "product15t.webp",
    name: "product15",
    title: "watches",
    description: "JACKETS & COATS",
    flag: "false",
  },


  {
    id: 16,
    image: "product16.webp",
    subImage1: "product16f.webp",
    subImage2: "product16s.webp",
    subImage3: "product16t.webp",
    name: "product16",
    title: "Shoes",
    description: "JACKETS & COATS",
    flag: "false",
  },

  
  {
    id: 17,
    image: "product17.webp",
    subImage1: "product17f.webp",
    subImage2: "product17s.webp",
    subImage3: "product17t.webp",
    name: "product17",
    title: "Men Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },


];

export default products;
