const products = [
  {
    id: 1,
    image: "product1.webp",
    subImage1: "product10.webp",
    subImage2: "product3.webp",
    subImage3: "product5.webp",
    name: "product1",
    title: "Women Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 2,
    image: "product2.webp",
    subImage1: "product3.webp",
    subImage2: "product3.webp",
    subImage3: "product3.webp",
    name: "product2",
    title: "Women Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 3,
    image: "product3.webp",
    subImage1: "product17.webp",
    subImage2: "subImg2.webp",
    subImage3: "subImg3.webp",
    name: "product3",
    title: "Men Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 4,
    image: "product4.webp",
    subImage1: "product17.webp",
    subImage2: "subImg2.webp",
    subImage3: "subImg3.webp",
    name: "product4",
    title: "Women Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 5,
    image: "product5.webp",
    subImage1: "product17.webp",
    subImage2: "subImg2.webp",
    subImage3: "subImg3.webp",
    name: "product5",
    title: "Women Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 6,
    image: "product6.webp",
    subImage1: "product17.webp",
    subImage2: "subImg2.webp",
    subImage3: "subImg3.webp",
    name: "product6",
    title: "Watches",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 7,
    image: "product7.webp",
    subImage1: "product17.webp",
    subImage2: "subImg2.webp",
    subImage3: "subImg3.webp",
    name: "product7",
    title: "Women Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 8,
    image: "product8.webp",
    subImage1: "product17.webp",
    subImage2: "subImg2.webp",
    subImage3: "subImg3.webp",
    name: "product8",
    title: "Women Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 9,
    image: "product9.webp",
    subImage1: "product17.webp",
    subImage2: "subImg2.webp",
    subImage3: "subImg3.webp",
    name: "product9",
    title: "Shoes",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 10,
    image: "product10.webp",
    subImage1: "product17.webp",
    subImage2: "subImg2.webp",
    subImage3: "subImg3.webp",
    name: "product10",
    title: "Women Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 11,
    image: "product11.webp",
    subImage1: "product17.webp",
    subImage2: "subImg2.webp",
    subImage3: "subImg3.webp",
    name: "product11",
    title: "Men Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 12,
    image: "product12.webp",
    subImage1: "product17.webp",
    subImage2: "subImg2.webp",
    subImage3: "subImg3.webp",
    name: "product12",
    title: "Men Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 13,
    image: "product13.webp",
    subImage1: "product17.webp",
    subImage2: "subImg2.webp",
    subImage3: "subImg3.webp",
    name: "product13",
    title: "Women Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 14,
    image: "product14.webp",
    subImage1: "product17.webp",
    subImage2: "subImg2.webp",
    subImage3: "subImg3.webp",
    name: "product14",
    title: "Women Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },

  {
    id: 15,
    image: "product15.webp",
    subImage1: "product17.webp",
    subImage2: "subImg2.webp",
    subImage3: "subImg3.webp",
    name: "product15",
    title: "watches",
    description: "JACKETS & COATS",
    flag: "false",
  },


  {
    id: 16,
    image: "product16.webp",
    subImage1: "product17.webp",
    subImage2: "subImg2.webp",
    subImage3: "subImg3.webp",
    name: "product16",
    title: "Women Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },

  
  {
    id: 17,
    image: "product17.webp",
    subImage1: "product17.webp",
    subImage2: "subImg2.webp",
    subImage3: "subImg3.webp",
    name: "product17",
    title: "Men Collection 2022",
    description: "JACKETS & COATS",
    flag: "false",
  },


];

export default products;
